/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disputes */
        get: operations["list_disputes_disputes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disputes/{dispute_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dispute Evidence */
        get: operations["list_dispute_evidence_disputes__dispute_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrow/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escrow Config */
        get: operations["escrow_config_escrow_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evidence */
        post: operations["create_evidence_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/indexer/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll Indexer */
        post: operations["poll_indexer_indexer_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Job */
        post: operations["prepare_job_jobs_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Evidence */
        get: operations["list_job_evidence_jobs__job_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{onchain_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__onchain_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{wallet_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_matches__wallet_address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Funnel Metrics */
        get: operations["funnel_metrics_metrics_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh All Reputations */
        post: operations["refresh_all_reputations_reputation_refresh_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/{wallet_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reputation */
        get: operations["get_reputation_reputation__wallet_address__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/{wallet_address}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Reputation */
        post: operations["refresh_reputation_reputation__wallet_address__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Swipe */
        post: operations["create_swipe_swipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{wallet_address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__wallet_address__get"];
        /** Upsert User */
        put: operations["upsert_user_users__wallet_address__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DisputeRead */
        DisputeRead: {
            /** Arbitrator Wallet */
            arbitrator_wallet: string;
            /** Evidence Hash */
            evidence_hash: string | null;
            /** Freelancer Share Bps */
            freelancer_share_bps: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Milestone Id
             * Format: uuid
             */
            milestone_id: string;
            /** Onchain Dispute Id */
            onchain_dispute_id: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By Wallet */
            opened_by_wallet: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Status */
            status: string;
        };
        /** EscrowConfigRead */
        EscrowConfigRead: {
            /** Chain Id */
            chain_id: number;
            /** Escrow Arbitrator */
            escrow_arbitrator: string;
            /** Escrow Contract Address */
            escrow_contract_address: string;
            /** Usdc Contract Address */
            usdc_contract_address: string;
        };
        /** EvidenceCreateRequest */
        EvidenceCreateRequest: {
            /** Body */
            body: string;
            /**
             * Content Type
             * @default text/plain
             */
            content_type: string;
            /** Dispute Id */
            dispute_id?: string | null;
            /**
             * File Name
             * @default evidence.txt
             */
            file_name: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Milestone Id */
            milestone_id?: string | null;
            /** Uploader Wallet */
            uploader_wallet: string;
            /**
             * Visibility
             * @default private
             */
            visibility: string;
        };
        /** EvidenceRead */
        EvidenceRead: {
            /** Content Type */
            content_type: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dispute Id */
            dispute_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Milestone Id */
            milestone_id: string | null;
            /** Sha256 Hash */
            sha256_hash: string;
            /** Size Bytes */
            size_bytes: number | null;
            /** Storage Uri */
            storage_uri: string;
            /** Uploader Wallet */
            uploader_wallet: string;
            /** Visibility */
            visibility: string;
        };
        /** FunnelMetricsRead */
        FunnelMetricsRead: {
            /** Disputes Opened */
            disputes_opened: number;
            /** Jobs Completed */
            jobs_completed: number;
            /** Jobs Created */
            jobs_created: number;
            /** Jobs Disputed */
            jobs_disputed: number;
            /** Jobs Funded */
            jobs_funded: number;
            /** Milestones Approved */
            milestones_approved: number;
            /** Total Matches */
            total_matches: number;
            /** Total Swipes */
            total_swipes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexerPollRead */
        IndexerPollRead: {
            /** Latest Block */
            latest_block: number;
        };
        /** JobPrepareRead */
        JobPrepareRead: {
            /** Chain Id */
            chain_id: number;
            /** Escrow Contract Address */
            escrow_contract_address: string;
            /** Freelancer Wallet */
            freelancer_wallet: string;
            /** Job Id */
            job_id: string;
            /** Milestone Amounts Raw */
            milestone_amounts_raw: string[];
            /** Total Amount Raw */
            total_amount_raw: string;
            /** Usdc Contract Address */
            usdc_contract_address: string;
        };
        /** JobPrepareRequest */
        JobPrepareRequest: {
            /** Freelancer Wallet */
            freelancer_wallet: string;
            /** Job Id */
            job_id?: string | null;
            /** Milestone Amounts Raw */
            milestone_amounts_raw: string[];
        };
        /** JobRead */
        JobRead: {
            /** Chain Id */
            chain_id: number;
            /** Client Wallet */
            client_wallet: string;
            /** Contract Address */
            contract_address: string;
            /** Freelancer Wallet */
            freelancer_wallet: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Milestones
             * @default []
             */
            milestones: components["schemas"]["MilestoneRead"][];
            /** Onchain Job Id */
            onchain_job_id: string;
            /** Public Summary */
            public_summary: string | null;
            /** Released Amount Raw */
            released_amount_raw: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Token Address */
            token_address: string;
            /** Total Amount Raw */
            total_amount_raw: string;
        };
        /** MatchRead */
        MatchRead: {
            job: components["schemas"]["JobRead"];
            swipe: components["schemas"]["SwipeRead"];
        };
        /** MilestoneRead */
        MilestoneRead: {
            /** Amount Raw */
            amount_raw: string;
            /** Evidence Hash */
            evidence_hash: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onchain Milestone Id */
            onchain_milestone_id: string;
            /** Review Deadline */
            review_deadline: string | null;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Title */
            title: string | null;
        };
        /** ReputationRead */
        ReputationRead: {
            /** Completed Jobs */
            completed_jobs: number;
            /** Direct Approval Rate Bps */
            direct_approval_rate_bps: number;
            /** Dispute Rate Bps */
            dispute_rate_bps: number;
            /** Repeat Client Count */
            repeat_client_count: number;
            /** Updated At */
            updated_at?: string | null;
            /** Verified Volume Tier */
            verified_volume_tier: string;
            /** Wallet Address */
            wallet_address: string;
        };
        /** SwipeCreateRequest */
        SwipeCreateRequest: {
            /** Actor Wallet */
            actor_wallet: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Direction */
            direction: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** SwipeRead */
        SwipeRead: {
            /** Actor Wallet */
            actor_wallet: string;
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Profile Visibility */
            profile_visibility: string;
            /** Role Preference */
            role_preference: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Wallet Address */
            wallet_address: string;
        };
        /** UserUpsertRequest */
        UserUpsertRequest: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Profile Visibility
             * @default public
             */
            profile_visibility: string;
            /**
             * Role Preference
             * @default both
             */
            role_preference: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_disputes_disputes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"][];
                };
            };
        };
    };
    list_dispute_evidence_disputes__dispute_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escrow_config_escrow_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscrowConfigRead"];
                };
            };
        };
    };
    create_evidence_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    poll_indexer_indexer_poll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerPollRead"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"][];
                };
            };
        };
    };
    prepare_job_jobs_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPrepareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPrepareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_evidence_jobs__job_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__onchain_job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                onchain_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches__wallet_address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funnel_metrics_metrics_funnel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelMetricsRead"];
                };
            };
        };
    };
    refresh_all_reputations_reputation_refresh_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRead"][];
                };
            };
        };
    };
    get_reputation_reputation__wallet_address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_reputation_reputation__wallet_address__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_swipe_swipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwipeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwipeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__wallet_address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_user_users__wallet_address__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
